# docs/swagger.yaml
openapi: 3.0.0
info:
  title: Task Management API
  version: 1.0.0
  description: API documentation for the Task Management System
servers:
  - url: http://localhost:5050/api
paths:
  /tasks:
    get:
      summary: Get all tasks
      security:
        - bearerAuth: []
      responses:
        "200":
          description: A list of tasks
    post:
      summary: Create a new task
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Task"
      responses:
        "201":
          description: Task created
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Task:
      type: object
      required:
        - title
        - description
      properties:
        title:
          type: string
        description:
          type: string
        status:
          type: string
          enum: [pending, in-progress, completed]
        priority:
          type: string
          enum: [low, medium, high]
        dueDate:
          type: string
          format: date-time
        assignedTo:
          type: string
        projectId:
          type: string
